{{- if .Values.mongo.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.pvc.size }}
  storageClassName: {{ .Values.mongo.pvc.storageClassName | quote }}
{{- end }}
