apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mongo.port }}
          volumeMounts:
            {{- if .Values.mongo.pvc.enabled }}
            - name: mongo-storage
              mountPath: /data/db
            {{- end }}
      volumes:
        {{- if .Values.mongo.pvc.enabled }}
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
  type: ClusterIP
