apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: movies
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.storage.size | default "5Gi" }}
  storageClassName: {{ .Values.mongo.storage.storageClassName | quote }}
